version: "3"

services:
  mysqldb:
    image: mysql:latest
    restart: always
    hostname: mysqldb
    environment:
      MYSQL_DATABASE: summer
      MYSQL_ROOT_PASSWORD: 1224
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis_docker
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis/data:/data
      - ./db/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./db/redis/init:/docker-entrypoint-initdb.d
      #- ./db/redis/log:/var/log/redis


  backend:
    #image: yuntaehyeon/speech #docker hub에 올릴 때
    build:
      context: .
      dockerfile: Dockerfile #image 사용하면 주석처리
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
      - redis
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh mysqldb:3306 -s -t 100
        java -jar /app.jar
